### ISSUE TITLE
Upgrade routine to change meta keys to match RCP

### ISSUE THREAD

**Issue by ashleyfae** [restrictcontentpro/restrict-content#13]
Current key is `rcUserLevel`. The one RCP uses is `rcp_user_level`. If we use the same keys then the upgrade experience will be seamless and old posts will still be restricted to the correct role.

- [x] Store version number.
- [x] Upgrade routine to update data.
- [x] Filter on `get_post_meta()` for backwards compatibility.

**Comment by mindctrl** [comment]
PR: #21. Tested this on a site with 11k records and it worked well.
